# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.2'
use_frameworks!

target 'moak' do
    pod 'Alamofire'
    pod 'BubbleTransition'
    pod 'MBProgressHUD'
    pod 'KCOrderedAccessorFix'
    pod 'DeployGateSDK'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'Firebase'
    pod 'FirebaseDatabase'
    pod 'FirebaseAuth'
    pod 'FirebaseStorage'
    pod 'FirebaseUI/Google'
    pod 'Crashlytics'
    pod 'SideMenu'
    pod 'lottie-ios'
    pod 'NotificationBannerSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end

target 'moak WatchKit App' do
    platform :watchos, '3.0'
end

target 'moak WatchKit Extension' do
    platform :watchos, '3.0'
end
