# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'moak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'Alamofire'
    pod 'BubbleTransition'
    pod 'MBProgressHUD'
    pod 'KCOrderedAccessorFix'
    pod 'DeployGateSDK'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'Firebase'
    pod 'FirebaseDatabase'
    pod 'FirebaseAuth'
    pod 'FirebaseStorage'
    #pod 'FirebaseUIGoogle'
    pod 'Crashlytics'
    pod 'SideMenu'
    pod 'lottie-ios'
    pod 'NotificationBannerSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

end

target 'moak WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :watchos, '3.0'
  use_frameworks!

  # Pods for moak WatchKit App

end

target 'moak WatchKit Extension' do    
  # Comment the next line if you don't want to use dynamic frameworks
  platform :watchos, '3.0'
  use_frameworks!

  # Pods for moak WatchKit Extension

end
